server:
  port: 5004

spring:
  application:
    name: job-portal-resume-service

  datasource:
    url: jdbc:postgresql://localhost:5432/job_portal_Resume_DB
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect