server:
  port: 5004

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/job_portal_Resume_DB
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver